{% set version = "1.9.2" %}

package:
  name: audi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz
  sha256: 4888205cfc7c8ffe15485b90d151cf6f296fc65c58d3c92ba57da8ab43c17279

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
    - clang      # [win]
    - ninja      # [win]
  host:
    - boost-cpp
    - eigen
    - obake-devel
    - mppp
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - eigen

test:
  commands:
    - test -f

about:
  home: http://darioizzo.github.io/audi/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'C++ header only library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
