{% set version = "1.10.0" %}

package:
  name: audi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz
  sha256: bd74e6040b6de88d4cc2caaa5b621b0ca334e6e657f25e95a77010caf140ca09

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
    - clang      # [win]
    - ninja      # [win]
  host:
    - libboost-devel
    - eigen
    - obake-devel
    - mppp
  run:
    - eigen
  run_constrained:
    # obake uses abseil headers, which require 10.13

test:
  commands:
    - test -f

about:
  home: http://darioizzo.github.io/audi/
  license: GPL-2.0-only OR GPL-3.0-only OR LGPL-3.0-only
  license_file:
    - COPYING.gpl3
    - COPYING.lgpl3
  summary: 'C++ header only library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'
  dev_url: https://github.com/darioizzo/audi

extra:
  recipe-maintainers:
    - darioizzo
