{% set version = "1.6.4" %}

package:
  name: audi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz
  sha256: d4fcd1fec114a30f16e4b7c13594005da5c24499eca3741f7dc3dd4bb3be5157

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - eigen
    - piranha 0.11
    - mppp 0.12
  run:
    - boost-cpp
    - eigen
    - piranha 0.11
    - mppp 0.12

test:
  commands:
    - test -f

about:
  home: http://darioizzo.github.io/audi/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'C++ header only library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
